### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shapkarin** [shapkarin/tensorflow.faker.js#1]
- [ ] Generated sentences from books
- [ ] Persons names based on different data
- [ ] Number ranges
- [ ] UUIDs
- [ ] Way to describe seeds of generated data
- [ ] Connected, categorized data
